model:
  vision:
    model_name_or_path: openai/clip-vit-large-patch14-336
    feature_pool: patch
    freeze: false
  language:
    model_name_or_path: openbmb/OmniLMM-12B
    freeze: false
    trust_remote_code: true
  projector:
    projector_type: mlp2x_gelu
    in_dim: 1024
    out_dim: 4096
    hidden_dim: 4096
    dropout: 0.0
